### PR TITLE
Remove console logging

### PR DESCRIPTION
**Pull request by constcrist**
Use `terser` and bash script to recompress the build and remove the `console.*` statements.
see issue:
https://github.com/intuitivelabs/intuitive-issues/issues/358

### CODE REVIEW

**Comment by constcrist** [comment]
the files w/o console statement are in:
```
cco@firiel:~/github.com/moki/Moki/client (remove-console)$ ls -al build/static/js/
total 15004
drwxrwxr-x 2 cco cco    4096 Jul  6 18:55 .
drwxrwxr-x 6 cco cco    4096 Jul  6 18:55 ..
-rw-rw-r-- 1 cco cco 2697252 Jul  6 18:55 2.747c3be0.chunk.js
-rw-rw-r-- 1 cco cco   25009 Jul  6 18:55 2.747c3be0.chunk.js.LICENSE.txt
-rw-rw-r-- 1 cco cco 9434179 Jul  6 18:55 2.747c3be0.chunk.js.map
-rw-rw-r-- 1 cco cco  208689 Jul  6 18:55 3.ffc95ef1.chunk.js
-rw-rw-r-- 1 cco cco     811 Jul  6 18:55 3.ffc95ef1.chunk.js.LICENSE.txt
-rw-rw-r-- 1 cco cco  434861 Jul  6 18:55 3.ffc95ef1.chunk.js.map
-rw-rw-r-- 1 cco cco   17846 Jul  6 18:55 4.50bf22b2.chunk.js
-rw-rw-r-- 1 cco cco     182 Jul  6 18:55 4.50bf22b2.chunk.js.LICENSE.txt
-rw-rw-r-- 1 cco cco   75417 Jul  6 18:55 4.50bf22b2.chunk.js.map
-rw-rw-r-- 1 cco cco 1182157 Jul  6 18:55 main.b4c2c3ca.chunk.js
-rw-rw-r-- 1 cco cco 1231421 Jul  6 18:55 main.b4c2c3ca.chunk.js.map
-rw-rw-r-- 1 cco cco    2330 Jul  6 18:55 runtime-main.5ea1aa8e.js
-rw-rw-r-- 1 cco cco   12441 Jul  6 18:55 runtime-main.5ea1aa8e.js.map
```

the original ones are in:
```
cco@firiel:~/github.com/moki/Moki/client (remove-console)$ ls -al build/static/js_orig/
total 14856
drwxrwxr-x 2 cco cco    4096 Jul  6 18:55 .
drwxrwxr-x 6 cco cco    4096 Jul  6 18:55 ..
-rw-rw-r-- 1 cco cco 2708318 Jul  6 18:55 2.747c3be0.chunk.js
-rw-rw-r-- 1 cco cco   25009 Jul  6 18:55 2.747c3be0.chunk.js.LICENSE.txt
-rw-rw-r-- 1 cco cco 9380522 Jul  6 18:55 2.747c3be0.chunk.js.map
-rw-rw-r-- 1 cco cco  209696 Jul  6 18:55 3.ffc95ef1.chunk.js
-rw-rw-r-- 1 cco cco     811 Jul  6 18:55 3.ffc95ef1.chunk.js.LICENSE.txt
-rw-rw-r-- 1 cco cco  432077 Jul  6 18:55 3.ffc95ef1.chunk.js.map
-rw-rw-r-- 1 cco cco   17990 Jul  6 18:55 4.50bf22b2.chunk.js
-rw-rw-r-- 1 cco cco     182 Jul  6 18:55 4.50bf22b2.chunk.js.LICENSE.txt
-rw-rw-r-- 1 cco cco   69054 Jul  6 18:55 4.50bf22b2.chunk.js.map
-rw-rw-r-- 1 cco cco 1182676 Jul  6 18:55 main.b4c2c3ca.chunk.js
-rw-rw-r-- 1 cco cco 1127792 Jul  6 18:55 main.b4c2c3ca.chunk.js.map
-rw-rw-r-- 1 cco cco    2382 Jul  6 18:55 runtime-main.5ea1aa8e.js
-rw-rw-r-- 1 cco cco   12511 Jul  6 18:55 runtime-main.5ea1aa8e.js.map
```

**Comment by constcrist** [comment]
@vladabroz pls. make a build and deploy it. I have never tested if the build actually works. we may have surprises due to side effects after removing `console.*` statements.

**Comment by constcrist** [comment]
`moki-client-dev.spec` tested with jenkins job:
https://jks.intuitivelabs.com:8443/view/moki/job/moki-client-dev-manual-branch/
and deployed manually on ` vbpri.d.intuitivelabs.com`. see jenkins logs here:
https://jks.intuitivelabs.com:8443/view/moki/job/moki-client-dev-manual-branch/17/console

**Comment by constcrist** [comment]
moki-client.spec tested with jenkins job:
https://jks.intuitivelabs.com:8443/view/moki/job/moki-client-manual-branch/127/console
and deployed manually on vbpri.d.intuitivelabs.com.

**Comment by vladabroz** [comment]
also, are you going to split the spec files for the **server** part too?

**Comment by constcrist** [comment]
> also, are you going to split the spec files for the **server** part too?

I have not looked at it yet. I will not split it in this PR anyways.

**Pull request merged**
